from PyQt5 import QtCore, QtGui, QtWidgets
import icon_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 733)
        MainWindow.setStyleSheet("background-color: rgb(35,35,35);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.central_main = QtWidgets.QFrame(self.centralwidget)
        self.central_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.central_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_main.setObjectName("central_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.central_main)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.central_main)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 100, 0, 0)
        self.horizontalLayout_5.setSpacing(50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(80)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(220, 150))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Youtube_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.frame_2 = QtWidgets.QFrame(self.central_main)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 50)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.url_entry = QtWidgets.QLineEdit(self.frame_2)
        self.url_entry.setMinimumSize(QtCore.QSize(600, 45))
        self.url_entry.setMaximumSize(QtCore.QSize(800, 45))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.url_entry.setFont(font)
        self.url_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left: 15px;")
        self.url_entry.setObjectName("url_entry")
        self.horizontalLayout_4.addWidget(self.url_entry)
        self.button_convert = QtWidgets.QPushButton(self.frame_2)
        self.button_convert.setMinimumSize(QtCore.QSize(115, 0))
        self.button_convert.setMaximumSize(QtCore.QSize(115, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_convert.setFont(font)
        self.button_convert.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_convert.setStyleSheet("border-radius: 20px;\n"
"color: white;\n"
"background-color: rgb(255, 0, 0);")
        self.button_convert.setObjectName("button_convert")
        self.horizontalLayout_4.addWidget(self.button_convert)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.frame_3 = QtWidgets.QFrame(self.central_main)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 15, 0, 15)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_thumbnail = QtWidgets.QFrame(self.frame_3)
        self.frame_thumbnail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_thumbnail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thumbnail.setObjectName("frame_thumbnail")
        self.frame_thumbnail.setMaximumSize(640, 360)
        self.frame_thumbnail.setMinimumSize(640, 360)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_thumbnail)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.thumbnail_label = QtWidgets.QLabel(self.frame_thumbnail)
        self.thumbnail_label.setMinimumSize(QtCore.QSize(640, 360))
        self.thumbnail_label.setMaximumSize(QtCore.QSize(640, 360))
        self.thumbnail_label.setStyleSheet("")
        self.thumbnail_label.setText("")
        self.thumbnail_label.setScaledContents(True)
        self.thumbnail_label.setObjectName("thumbnail_label")
        self.verticalLayout_4.addWidget(self.thumbnail_label)
        self.horizontalLayout_6.addWidget(self.frame_thumbnail)
        self.title_frame = QtWidgets.QFrame(self.frame_3)
        self.title_frame.setMinimumSize(QtCore.QSize(450, 360))
        self.title_frame.setMaximumSize(QtCore.QSize(850, 360))
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("titel_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.title_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setMinimumSize(QtCore.QSize(450, 360))
        self.title_label.setMaximumSize(QtCore.QSize(650, 360))
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)  # Yazıyı sola ve üste yasla
        self.title_label.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("")
        self.title_label.setText("")
        self.title_label.setObjectName("titel_label")
        self.title_label.setStyleSheet("color: white;")
        self.verticalLayout_5.addWidget(self.title_label)
        self.horizontalLayout_6.addWidget(self.title_frame)
        self.verticalLayout_3.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frame_4 = QtWidgets.QFrame(self.central_main)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setContentsMargins(0, 30, 0, 30)
        self.horizontalLayout_7.setSpacing(50)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setMinimumSize(QtCore.QSize(250, 35))
        self.comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBox.setStyleSheet("color: white;")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setMinimumSize(QtCore.QSize(220, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(220, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(47, 171, 51);\n"
"color: white;\n"
"border-radius: 20px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout.addWidget(self.central_main)
        self.central_right = QtWidgets.QFrame(self.centralwidget)
        self.central_right.setMinimumSize(QtCore.QSize(350, 0))
        self.central_right.setMaximumSize(QtCore.QSize(350, 16777215))
        self.central_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.central_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_right.setObjectName("central_right")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.central_right)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.right_menu = QtWidgets.QFrame(self.central_right)
        self.right_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu.setObjectName("right_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.right_menu_content_frame = QtWidgets.QFrame(self.right_menu)
        self.right_menu_content_frame.setStyleSheet("")
        self.right_menu_content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu_content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu_content_frame.setObjectName("right_menu_content_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_menu_content_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.right_menu_top = QtWidgets.QFrame(self.right_menu_content_frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.right_menu_top.setFont(font)
        self.right_menu_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu_top.setObjectName("right_menu_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.right_menu_top)
        self.horizontalLayout_3.setContentsMargins(0, 20, 0, 20)
        self.horizontalLayout_3.setSpacing(25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_list_title = QtWidgets.QLabel(self.right_menu_top)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_list_title.setFont(font)
        self.label_list_title.setStyleSheet("color:white;")
        self.label_list_title.setScaledContents(False)
        self.label_list_title.setObjectName("label_list_title")
        self.horizontalLayout_3.addWidget(self.label_list_title)
        self.button_delete = QtWidgets.QPushButton(self.right_menu_top)
        self.button_delete.setMaximumSize(QtCore.QSize(40, 40))
        self.button_delete.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_delete.setStyleSheet("border: none;")
        self.button_delete.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/delete_24dp_E8EAED_FILL1_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.button_delete.setIcon(icon)
        self.button_delete.setIconSize(QtCore.QSize(35, 35))
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout_3.addWidget(self.button_delete)
        self.verticalLayout_2.addWidget(self.right_menu_top, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.right_menu_content = QtWidgets.QFrame(self.right_menu_content_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_menu_content.sizePolicy().hasHeightForWidth())
        self.right_menu_content.setSizePolicy(sizePolicy)
        self.right_menu_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu_content.setObjectName("right_menu_content")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.right_menu_content)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.right_menu_content)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.list_area = QtWidgets.QWidget()
        self.list_area.setGeometry(QtCore.QRect(0, 0, 340, 639))
        self.list_area.setObjectName("list_area")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.list_area)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.list_media_frame = QtWidgets.QFrame(self.list_area)
        self.list_media_frame.setMinimumSize(QtCore.QSize(0, 90))
        self.list_media_frame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.list_media_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_media_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_media_frame.setObjectName("list_media_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.list_media_frame)
        self.verticalLayout_8.setContentsMargins(10, 0, 0, 5)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea.setWidget(self.list_area)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.right_menu_content)
        self.verticalLayout.addWidget(self.right_menu_content_frame)
        self.horizontalLayout_2.addWidget(self.right_menu)
        self.horizontalLayout.addWidget(self.central_right)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MyTube"))
        self.url_entry.setPlaceholderText(_translate("MainWindow", "URL"))
        self.button_convert.setText(_translate("MainWindow", "CONVERT"))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.label_list_title.setText(_translate("MainWindow", "Downloads"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
